chore : added eb installation.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,6 +10,21 @@ jobs:
       - checkout
       - aws-cli/setup
       - run:
+          command: |
+            export PIP=$(which pip pip3 | head -1)
+            if [[ -n $PIP ]]; then
+              if which sudo > /dev/null; then
+                sudo $PIP install awsebcli --upgrade
+              else
+                # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+                $PIP install awsebcli --upgrade --user
+              fi
+            else
+              echo "Unable to install AWS EB CLI. Please install pip."
+              exit 1
+            fi
+          name: Installing EB CLI
+      - run:
           name: Front-End Install
           command: |
             npm run frontend:install
